name: build

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - "dist/**"
      - "**.md"

jobs:
  build:
    name: build images
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: docker buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@e01797ad2ea9a981005ad58c99afa8d842e3d3eb # v1
        with:
          buildx-version: latest
          qemu-version: latest

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
