name: build

on:
  push:
    tags:
      - "v*.*.*"
      - "*.*.*"
    paths-ignore:
      - "dist/**"
      - "**.md"

jobs:
  build:
    name: build images and push
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: docker buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@e01797ad2ea9a981005ad58c99afa8d842e3d3eb # v1
        with:
          buildx-version: latest
          qemu-version: latest

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: repo info
        id: vars
        run: |
          echo ::set-output name=repo_tag::${GITHUB_REF#refs/*/}

      - name: build and push (tag)
        if: startsWith( github.ref, 'refs/tags/')
        run: make build-push
        env:
          VERSION: ${{steps.vars.outputs.repo_tag}}

      - name: build and push (latest)
        if: startsWith( github.ref, 'refs/tags/')
        run: make build-push
        env:
          VERSION: latest

  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2
        with:
          go-version: 1.18
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@b953231f81b8dfd023c58e0854a721e35037f28b # v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
